# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j0Lwo4y3tk9K5CcmmsCH-WNaJ3GWFL1b
"""

#SUMA
def sum_numbers():
    # Ask for user input
    print("Suma")
    a = float(input("Escribe el primer número: "))
    b = float(input("Escribe el segundo número: "))

    # Calculate the sum
    result = a + b

    # Return the result
    return result

# Call the function and print the result
result = sum_numbers()
print("La suma es:", result)

# Resta
numero1 = float(input("Por favor ingresar el primer número "))

numero2 = float(input("Por favor ingresar el segundo número "))

resultado = numero1 - numero2

print("El resultado de los siguientes numeros es", resultado)

#Division
def divide_numbers():
    try:

        numerator = float(input("Escribe el numerador: "))
        denominator = float(input("Escribe el denominador: "))


        result = numerator / denominator


        print(f"El resultado de {numerator} / {denominator} es: {result}")

    except ZeroDivisionError:

        print("Error: La division entre 0 no es posible.")

    except ValueError:

        print("Error: Por favor ingrese solo valores numericos.")

divide_numbers()