# -*- coding: utf-8 -*-
"""Codigo para resta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18vwByJFo9DOKA2FpJBhXg96RxV0MxOS0
"""

numero1 = float(input("Por favor ingresar el primer número "))

numero2 = float(input("Por favor ingresar el segundo número "))

resultado = numero1 - numero2

print("El resultado de los siguientes numeros es", resultado)